name: CI
on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: opensuse/leap:15.4
    steps:
      - name: Update packages
        run: zypper --non-interactive --gpg-auto-import-keys ref
      - name: Install openSUSE dependencies
        run: zypper --non-interactive --gpg-auto-import-keys install lsb-release tar gzip
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
